### ISSUE TITLE
[USER-STORY] Get to know the decision maker.

### ISSUE THREAD

**Issue by apluskett** [MetroCS/cs3250_practice#75]
Get to know the decision maker.

# User Story

## Story
As a Maintainer<br>
I want some way to get to know the decision maker <br>
so that the product can better rank the decision maker's outcomes.

## Acceptance Criteria
_Choose either rules or scenarios and ensure they are verifiable from the perspective of the stakeholder_

### Rules
* Gives the developers quantifiable information
* Avoids being invasive as much as possible
* Gives better understanding as to the how the Decision Maker makes choices

## Supporting Information
I believe we need to have a way to understand how the Decision Maker makes their choices so that way we have a way to better rank their choices and so that we can be able to explain why each choice is ranked they way they are. I believe a possible, but not absolute, option could be a quick 5 minute survey in which we can ask the decision maker to make some choices to give us some data that we can then use in order to rank their choices. This would allows us to allow us to explain and rank choices in the same manner that the decision maker would.  

### Depends On   
None at this time  
### Dependents  
#60

**Comment by jody** [comment]
This is an interesting user story! The desire for developers to know and understand the needs and wants of the decision-makers is an important goal of product development. This seems to concern the software life-cycle model used to develop the product rather than describing an attribute of the product.  Perhaps this can be rewritten to address what kinds of documentation are needed by developers.  

The acceptance criteria seem to offer a solution design rather than a way to determine if any given solution satisfies the user story. That needs to be left up to the solution provider (typically the developers).

The supporting information identifies a lack of clarity with respect to what the client decision-makers want. This will help us focus on getting better information from our clients! (IA survey may or may not be the most effective way to do so.)

**Comment by apluskett** [comment]
I have updated the user story for most of your points. I am still working through what information we can extrapolate from the user, and such that it is quantifiable, that will better help us help the decision maker.

**Comment by jody** [comment]
I'm not sure there's much more to be done on this as a user story. Refocusing on developer documentation seems potentially more effective.

**Comment by jody** [comment]
Please change the stakeholder type to [Maintainer](https://metrocs.github.io/cs3250_practice/).

This issue involves identifying the characteristics of the Decision-Maker stakeholder. A more appropriate title for this user story would be "Document Characteristics of Decision-Makers". The story can then be rewritten to match.

At the moment, the only documented information we have is what's found in the [Product Overview](https://metrocs.github.io/cs3250_practice/ProductOverview.html).

The acceptance criteria also need to be _measurable:_ the comprise a way to determine whether or not the product satisfies the user story. From the perspective of the Maintainer, the product is our repository and associated project-management information.

**Comment by jody** [comment]
Additional documentation now exists in [DSSProcess.md](https://github.com/MetroCS/cs3250_practice/blob/main/decision_support/DSSProcess.md)
