### ISSUE TITLE
[USER-STORY] Document Contribution Guidelines

### ISSUE THREAD

**Issue by Donsch377** [MetroCS/cs3250_practice#77]
# User Story

## Story
As a _Maintainer_ <br>
I want _a comprehensive guide on contributing to the project_ <br>
so that _I understand how to effectively contribute and collaborate with other contributors_.

### Rules
* A document titled "Contribute to Our Project" exists in the project's repository under the `/docs` directory.
* The document includes sections on expected conduct, adding issues, workflow process, discussion management, development conventions, and project technologies.
* The document is accessible from the project's README file via a direct link under a section titled "How to Contribute."

## Supporting Information
_See similar documentation efforts in projects like "Contributing to the ImageLab Project" and "Contributing to the Redistricting Project."_

### Dependents  
_#65_

**Comment by jody** [comment]
**About the Story:**  
How is. 
_"I want a comprehensive guide on contributing to the project"_ 
significantly different from. 
_"I want information about contributing to the project"?_

It seems like "comprehensive" or "guide" or both are significant. But the distinction is unclear. This feels more like a restating of #65 rather than a sub-story of that epic.  Please clarify.

<hr />

 **About the Acceptance Criteria**
These seem to constrain the potential solutions without explaining why other solutions are not acceptable.  

_A document titled "Contribute to Our Project" exists in the project's repository under the /docs directory._. 

Why is that specific title necessary for the Maintainer? (Why would any other title not be acceptable?)
Similarly, why is the only acceptable section heading "How to Contribute"?  These seem to unnecessarily restrict acceptable solutions. (The user story and its acceptance criteria are expectede to describe **what** needs to be achieved, and allow the developers to determine **how** to achieve it.)

Similarly, why does the document need to reside in the /docs directory?  Note that a /docs is used for the published website via the "website" branch. 

Another aspect that seems over-constrained is that all of the information must be contained in the same file. That precludes solutions that organize the information into multiple, linked files.

**Comment by jody** [comment]
This user story is superseded by #81.
