### ISSUE TITLE
[USER-STORY] Create Data Stucture to Store Decisions and Their Priority

### ISSUE THREAD

**Issue by jmaestas7** [MetroCS/cs3250_practice#86]
# User Story

## Story
As a Developer <br>
I want to create a data structure to store decisions by priority <br>
so that decisions by priority can be stored in a way where higher-priority decisions are at the top.

## Acceptance Criteria
- The method used should be able to store both the decision or intake the decision object and order them priority
- When the data structure is accessed every decision should have an attributed priority level.

### Rules
* Every decision should have an associated priority level
* The object containing the decision with higher priorities are ordered in order from most to least

## Supporting Information
_[Relevant information, context, resources, references]_

### Dependents  
#60

**Comment by jody** [comment]
As discussed, the story appears to specify an implementation (data structure) rather than an objective (output needed). The acceptance criteria are then written from the perspective of the story's user.

The choice of how the objective is accomplished is best left up to the implementer. (Our TDD model will account for automated testing of the implementation.)

**Comment by jody** [comment]
Closing as design rather than requirement.
